#!/usr/bin/env bash 

if [ -d /tmp/decidim/ ] ; then 
	cd /tmp/decidim/ 
	git pull origin master 
	cd - 
else 
	git clone https://github.com/decidim/decidim  /tmp/decidim/ 
fi

set -e

# TODO: add a comment about being autogenerated
cp /tmp/decidim/README.md README.md

#/tmp/decidim/docs/getting_started.md

cp /tmp/decidim/CHANGELOG.md about/changelog.md 
cp /tmp/decidim/CODE_OF_CONDUCT.md about/code-of-conduct.md
cp /tmp/decidim/CONTRIBUTING.md about/contributing.md 

# advanced
cp /tmp/decidim/docs/create_followers_from_comment_authors.md advanced/followers-from-comment-authors.md 
cp /tmp/decidim/docs/create_followers_from_resource_authors.md advanced/followers-from-resource-authors.md 
cp /tmp/decidim/docs/features_and_components.md advanced/features_and_components.md 
cp /tmp/decidim/docs/how_to_create_a_plugin.md advanced/how_to_create_a_plugin.md 
cp /tmp/decidim/docs/managing_translations_i18n.md advanced/managing_translations_i18n.md 
cp /tmp/decidim/docs/migrate_to_0.8.0.md advanced/migrate_to_0.8.0.md 
cp /tmp/decidim/docs/testing.md advanced/testing.md 
cp /tmp/decidim/docs/view_hooks.md advanced/view-hooks.md


# services
cp /tmp/decidim/docs/geocoding.md services/geocoding.md 
cp /tmp/decidim/docs/analytics.md services/analytics.md 
cp /tmp/decidim/docs/social_providers.md services/oauth-social-providers.md 


# modules
cp /tmp/decidim/decidim-accountability/README.md modules/decidim-module-accountability.md 
cp /tmp/decidim/decidim-admin/README.md modules/decidim-module-admin.md 
cp /tmp/decidim/decidim-api/README.md modules/decidim-module-api.md 
cp /tmp/decidim/decidim-assemblies/README.md modules/decidim-module-assemblies.md 
cp /tmp/decidim/decidim-budgets/README.md modules/decidim-module-budgets.md 
cp /tmp/decidim/decidim-comments/README.md modules/decidim-module-comments.md 
cp /tmp/decidim/decidim-core/README.md modules/decidim-module-core.md 
cp /tmp/decidim/decidim-design/README.md modules/decidim-module-design.md 
cp /tmp/decidim/decidim-dev/README.md modules/decidim-module-dev.md 
cp /tmp/decidim/decidim-meetings/README.md modules/decidim-module-meetings.md 
cp /tmp/decidim/decidim-pages/README.md modules/decidim-module-pages.md 
cp /tmp/decidim/decidim-participatory_processes/README.md modules/decidim-module-participatory_processes.md 
cp /tmp/decidim/decidim-proposals/README.md modules/decidim-module-proposals.md 
cp /tmp/decidim/decidim-surveys/README.md modules/decidim-module-surveys.md 
cp /tmp/decidim/decidim-system/README.md modules/decidim-module-system.md 
cp /tmp/decidim/decidim-verifications/README.md modules/decidim-module-verifications.md 


