#!/usr/bin/env bash 

set -e

DIR_TMP=/tmp/decidim-docs-build

function clone_or_update() {
    repo=$1
    dir_name=$(basename $repo)

    if [ -d ${DIR_TMP}/$dir_name/ ] ; then 
        cd ${DIR_TMP}/$dir_name/ 
        git pull origin master 
        cd - 
    else 
        git clone https://github.com/${repo} ${DIR_TMP}/$dir_name/ 
    fi
}


clone_or_update decidim/decidim

# TODO: add a comment about being autogenerated
cp ${DIR_TMP}/decidim/README.md README.md

#${DIR_TMP}/decidim/docs/getting_started.md

cp ${DIR_TMP}/decidim/CHANGELOG.md about/changelog.md 
cp ${DIR_TMP}/decidim/CODE_OF_CONDUCT.md about/code-of-conduct.md
cp ${DIR_TMP}/decidim/CONTRIBUTING.md about/contributing.md 

# advanced
cp ${DIR_TMP}/decidim/docs/create_followers_from_comment_authors.md advanced/followers-from-comment-authors.md 
cp ${DIR_TMP}/decidim/docs/create_followers_from_resource_authors.md advanced/followers-from-resource-authors.md 
cp ${DIR_TMP}/decidim/docs/features_and_components.md advanced/features_and_components.md 
cp ${DIR_TMP}/decidim/docs/how_to_create_a_plugin.md advanced/how_to_create_a_plugin.md 
cp ${DIR_TMP}/decidim/docs/managing_translations_i18n.md advanced/managing_translations_i18n.md 
cp ${DIR_TMP}/decidim/docs/migrate_to_0.8.0.md advanced/migrate_to_0.8.0.md 
cp ${DIR_TMP}/decidim/docs/testing.md advanced/testing.md 
cp ${DIR_TMP}/decidim/docs/view_hooks.md advanced/view-hooks.md

# services
cp ${DIR_TMP}/decidim/docs/geocoding.md services/geocoding.md 
cp ${DIR_TMP}/decidim/docs/analytics.md services/analytics.md 
cp ${DIR_TMP}/decidim/docs/social_providers.md services/oauth-social-providers.md 

# Internal official modules
cp ${DIR_TMP}/decidim/decidim-accountability/README.md modules/official/accountability.md 
cp ${DIR_TMP}/decidim/decidim-admin/README.md modules/official/admin.md 
cp ${DIR_TMP}/decidim/decidim-api/README.md modules/official/api.md 
cp ${DIR_TMP}/decidim/decidim-assemblies/README.md modules/official/assemblies.md 
cp ${DIR_TMP}/decidim/decidim-budgets/README.md modules/official/budgets.md 
cp ${DIR_TMP}/decidim/decidim-comments/README.md modules/official/comments.md 
cp ${DIR_TMP}/decidim/decidim-core/README.md modules/official/core.md 
cp ${DIR_TMP}/decidim/decidim-design/README.md modules/official/design.md 
cp ${DIR_TMP}/decidim/decidim-dev/README.md modules/official/dev.md 
cp ${DIR_TMP}/decidim/decidim-meetings/README.md modules/official/meetings.md 
cp ${DIR_TMP}/decidim/decidim-pages/README.md modules/official/pages.md 
cp ${DIR_TMP}/decidim/decidim-participatory_processes/README.md modules/official/participatory_processes.md 
cp ${DIR_TMP}/decidim/decidim-proposals/README.md modules/official/proposals.md 
cp ${DIR_TMP}/decidim/decidim-surveys/README.md modules/official/surveys.md 
cp ${DIR_TMP}/decidim/decidim-system/README.md modules/official/system.md 
cp ${DIR_TMP}/decidim/decidim-verifications/README.md modules/official/verifications.md 

# External official Modules
official_modules=(
    "sortitions"
    "blogs"
)
for i in "${official_modules[@]}" ; do
  clone_or_update decidim/decidim-module-${i}
  cp ${DIR_TMP}/decidim-module-${i}/README.md modules/official/${i}.md
done

clone_or_update decidim/decidim-initiatives
cp ${DIR_TMP}/decidim-initiatives/README.md modules/official/initiatives.md

clone_or_update decidim/decidim-results
cp ${DIR_TMP}/decidim-results/README.md modules/official/results.md

# Community Modules
clone_or_update ElectricThings/decidim-members
cp ${DIR_TMP}/decidim-members/README.md modules/community/members.md

clone_or_update OpenSourcePolitics/decidim-user-export
cp ${DIR_TMP}/decidim-user-export/README.md modules/community/user-export.md

clone_or_update podemos-info/decidim-module-votings
cp ${DIR_TMP}/decidim-module-votings/README.md modules/community/votings.md

clone_or_update podemos-info/decidim-module-crowdfundings
cp ${DIR_TMP}/decidim-module-crowdfundings/README.md modules/community/crowdfundings.md

clone_or_update HospitaletDeLlobregat/decidim-hospitalet
cp ${DIR_TMP}/decidim-hospitalet/decidim_hospitalet-surveys/README.md modules/community/surveys-hospitalet.md

clone_or_update AjuntamentdeBarcelona/decidim-barcelona
cp ${DIR_TMP}/decidim-barcelona/decidim-dataviz/README.md modules/community/dataviz-barcelona.md
cp ${DIR_TMP}/decidim-barcelona/decidim-debates/README.md modules/community/debates-barcelona.md

clone_or_update diputacioBCN/decidim-diba 
cp ${DIR_TMP}/decidim-diba/decidim-census/README.md modules/community/census.md
cp ${DIR_TMP}/decidim-diba/decidim-diba_census_api/README.md modules/community/verification-census-api.md

clone_or_update OpenSourcePolitics/decidim-efb 
cp ${DIR_TMP}/decidim-efb/decidim-polis/README.md modules/community/polis.md

# TODO: * [Verification Barcelona Census API](modules/community/verification-census-barcelona.md)
# TODO: members
